# Generated by Django 5.2.8 on 2025-11-28 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Nom d’icône (ex: 'bi-code', 'fa-paint-brush'). Optionnel.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de services',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Tag de service',
                'verbose_name_plural': 'Tags de services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price_min', models.PositiveIntegerField(help_text='Prix minimum en FCFA (ou autre devise).', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_max', models.PositiveIntegerField(help_text='Prix maximum en FCFA (ou autre devise).', validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('is_price_negotiable', models.BooleanField(default=False, help_text='Si actif, le client peut proposer un prix en dehors de la fourchette.')),
                ('delivery_time_min_days', models.PositiveIntegerField(default=3, help_text='Délai minimum (en jours) pour une commande standard.', validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_time_max_days', models.PositiveIntegerField(default=14, help_text='Délai maximum (en jours) que le prestataire accepte.', validators=[django.core.validators.MinValueValidator(1)])),
                ('revisions_included', models.PositiveIntegerField(default=1, help_text='Nombre de retours inclus dans le prix.', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('paused', 'En pause'), ('archived', 'Archivé'), ('blocked', 'Bloqué par l’admin')], default='active', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Visible dans la recherche'), ('unlisted', 'Accessible seulement via le lien')], default='public', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Permet de mettre certains services en avant dans la liste.')),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('completed_orders_count', models.PositiveIntegerField(default=0)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
                ('provider', models.ForeignKey(help_text='Utilisateur qui propose ce service (étudiant, entreprise ou autre).', on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='services', to='services.servicetag')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Vidéo (lien)')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/media/images/%Y/%m/%d/')),
                ('file', models.FileField(blank=True, null=True, upload_to='services/media/files/%Y/%m/%d/')),
                ('video_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.serviceoffer')),
            ],
            options={
                'verbose_name': 'Média de service',
                'verbose_name_plural': 'Médias de services',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.serviceoffer')),
            ],
            options={
                'verbose_name': 'FAQ de service',
                'verbose_name_plural': 'FAQ de services',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_title_snapshot', models.CharField(max_length=255)),
                ('provider_username_snapshot', models.CharField(max_length=150)),
                ('description_brief', models.CharField(blank=True, help_text='Contexte fourni par le client pour cette commande.', max_length=500)),
                ('agreed_price', models.PositiveIntegerField(help_text='Prix convenu en FCFA (ou autre devise).', validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('status', models.CharField(choices=[('pending', "En attente d'acceptation"), ('accepted', 'Acceptée'), ('in_progress', 'En cours'), ('delivered', 'Livrée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_actor', models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Prestataire'), ('platform', 'Plateforme')], max_length=10)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('max_revisions', models.PositiveIntegerField(default=0)),
                ('revisions_used', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(help_text='Utilisateur qui commande (client).', on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Utilisateur qui exécute (prestataire).', on_delete=django.db.models.deletion.CASCADE, related_name='service_sales', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.serviceoffer')),
            ],
            options={
                'verbose_name': 'Commande de service',
                'verbose_name_plural': 'Commandes de services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('status_change', 'Changement de statut'), ('system', 'Événement système'), ('note', 'Note interne')], default='status_change', max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='services.serviceorder')),
            ],
            options={
                'verbose_name': 'Événement de commande',
                'verbose_name_plural': 'Événements de commandes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Marqué pour modération (langage inapproprié, etc.).')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='services.serviceorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.serviceoffer')),
            ],
            options={
                'verbose_name': 'Avis sur un service',
                'verbose_name_plural': 'Avis sur les services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_services', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='services.serviceoffer')),
            ],
            options={
                'verbose_name': 'Service favori',
                'verbose_name_plural': 'Services favoris',
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status'], name='services_se_status_d2293e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['client'], name='services_se_client__3b997b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['provider'], name='services_se_provide_ef8083_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['service', 'status'], name='services_se_service_588a04_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['service', 'rating'], name='services_se_service_1926bf_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['status', 'visibility', 'is_featured'], name='services_se_status_d200bd_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['category', 'status'], name='services_se_categor_bb185f_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['provider', 'status'], name='services_se_provide_b23443_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['price_min', 'price_max'], name='services_se_price_m_b32bb9_idx'),
        ),
    ]
