# Generated by Django 5.2.8 on 2025-11-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicesearchalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='default_tags',
            field=models.ManyToManyField(blank=True, help_text='tags genere automatiquement pour cette categorie.', related_name='default_for_categories', to='services.servicetag'),
        ),
    ]
