# Generated by Django 5.2.8 on 2025-11-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_default_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='client_mark_complete',
            field=models.BooleanField(default=False, help_text="Le client a cliqué sur 'Terminer la commande'."),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='provider_mark_complete',
            field=models.BooleanField(default=False, help_text="Le prestataire a cliqué sur 'Terminer la commande'."),
        ),
    ]
