# Generated by Django 5.2.8 on 2025-11-29 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceorder_client_mark_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='single_active_order',
            field=models.BooleanField(default=False, help_text="Si coché, ce service ne peut avoir qu'une seule commande active à la fois. Les nouvelles commandes sont bloquées tant qu'une commande en cours existe."),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='agreed_price',
            field=models.PositiveIntegerField(blank=True, help_text='Prix convenu en FCFA (ou autre devise).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', "En attente d'acceptation"), ('accepted', 'Acceptée'), ('in_progress', 'En cours'), ('delivered', 'Livrée'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=20),
        ),
    ]
