# Generated by Django 5.2.8 on 2025-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceoffer_single_active_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='slug',
            field=models.SlugField(blank=True, help_text="Slug unique pour l'url du service", max_length=255, unique=True),
        ),
    ]
