# Generated by Django 5.2.8 on 2025-11-30 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceoffer_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteservice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='favoriteservice',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='favoriteservice',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
