# Generated by Django 5.2.8 on 2025-11-30 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_favoriteservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Expliquez le problème rencontré (escroquerie, non respect, insultes, etc.).')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_review', 'En cours de traitement'), ('resolved', 'Résolu'), ('rejected', 'Rejeté')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicereview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='servicereview',
            name='services_se_service_1926bf_idx',
        ),
        migrations.RemoveField(
            model_name='servicereview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='servicereview',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='servicereview',
            name='is_public',
        ),
        migrations.AddField(
            model_name='servicereview',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Client qui laisse l'avis.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='comment',
            field=models.TextField(blank=True, help_text='Commentaire (optionnel).', null=True),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='order',
            field=models.OneToOneField(help_text='Commande associée à cet avis.', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='services.serviceorder'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Note de 1 à 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='service',
            field=models.ForeignKey(help_text='Service évalué.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.serviceoffer'),
        ),
        migrations.AddField(
            model_name='serviceorderreport',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services.serviceorder'),
        ),
        migrations.AddField(
            model_name='serviceorderreport',
            name='reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorderreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='serviceorderreport',
            unique_together={('order', 'reporter')},
        ),
    ]
