# Generated by Django 5.2.8 on 2025-11-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_serviceorderreport_alter_servicereview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemedia',
            name='caption',
            field=models.CharField(blank=True, help_text='Petit titre/description du media', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL YOUTUBE,ETC', null=True),
        ),
    ]
