# Generated by Django 5.2.8 on 2025-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicemedia_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='services/files/%Y/%m/%d/'),
        ),
    ]
