# Generated by Django 5.2.8 on 2025-11-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_servicemedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='services/files/'),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/'),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Vidéo (lien)')], max_length=10),
        ),
    ]
