# Generated by Django 5.2.8 on 2025-12-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_providerpenaltylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='computed_total_price',
            field=models.PositiveIntegerField(blank=True, help_text='Total pack + extras (indicatif).', null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='extras_summary',
            field=models.TextField(blank=True, help_text='Résumé des options supplémentaires choisies.'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='extras_total_price',
            field=models.PositiveIntegerField(blank=True, help_text='Total des extras choisis.', null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='package_name',
            field=models.CharField(blank=True, help_text='Nom du pack choisi (Basique/Standard/Premium).', max_length=120),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='package_price',
            field=models.PositiveIntegerField(blank=True, help_text='Prix du pack choisi au moment de la commande.', null=True),
        ),
        migrations.CreateModel(
            name='ServiceExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text='Surcoût si le client choisit cette option.')),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='services.serviceoffer')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basic', 'Pack Basique'), ('standard', 'Pack Standard'), ('premium', 'Pack Premium')], default='basic', help_text='Type de pack (Basique / Standard / Premium).', max_length=20)),
                ('title', models.CharField(help_text='Nom affiché au client, ex: Pack Basique', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Ce qui est inclus dans ce pack.')),
                ('price', models.PositiveIntegerField(help_text='Prix proposé pour ce pack (en même devise que le service).')),
                ('delivery_time_days', models.PositiveIntegerField(default=1, help_text='Délai estimé pour ce pack.')),
                ('revisions', models.PositiveIntegerField(default=0, help_text='Nombre de révisions incluses pour ce pack.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.serviceoffer')),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
