# Generated by Django 5.2.8 on 2025-12-02 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_serviceorder_computed_total_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text="Durée typique d'une prestation (en minutes) pour un créneau réservé."),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='slot_max_clients',
            field=models.PositiveIntegerField(default=1, help_text='Nombre maximum de clients que tu peux gérer en parallèle sur un même créneau.'),
        ),
        migrations.AddField(
            model_name='serviceorderreport',
            name='appointment_end',
            field=models.DateTimeField(blank=True, help_text='Fin du créneau réservé pour cette commande.', null=True),
        ),
        migrations.AddField(
            model_name='serviceorderreport',
            name='appointment_start',
            field=models.DateTimeField(blank=True, help_text='Début du créneau réservé pour cette commande (si applicable).', null=True),
        ),
        migrations.CreateModel(
            name='ProviderVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('affects_chat', models.BooleanField(default=True, help_text='Si coché, le prestataire est aussi considéré indisponible pour le chat.')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProviderWeeklySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_parallel_orders', models.PositiveIntegerField(default=1, help_text='Nombre max de commandes simultanées dans ce créneau.')),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_slots', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, help_text="Si défini, ce créneau ne s'applique qu'à ce service.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_slots', to='services.serviceoffer')),
            ],
            options={
                'ordering': ['provider', 'weekday', 'start_time'],
            },
        ),
    ]
