# Generated by Django 5.2.8 on 2025-12-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_providertimeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffer',
            name='slot_duration_minutes',
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='average_duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=60, help_text="Durée typique d'une prestation (en minutes) pour un créneau réservé.", null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='creneau associe a un commancde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services.providertimeslot'),
        ),
    ]
