# Generated by Django 5.2.8 on 2025-12-03 04:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_serviceoffer_slot_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code interne du plan (ex: FREE, PRO, PREMIUM).', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nom affiché au prestataire.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du plan / avantages.', null=True)),
                ('monthly_price', models.PositiveIntegerField(default=0, help_text='Prix mensuel (ex: en FCFA). 0 = gratuit.')),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('max_active_services', models.PositiveIntegerField(default=1, help_text='Nombre maximum de services actifs.')),
                ('max_featured_services', models.PositiveIntegerField(default=0, help_text='Nombre de services mis en avant autorisés.')),
                ('max_urgent_orders_per_day', models.PositiveIntegerField(default=0, help_text='Nombre de commandes urgentes par jour autorisées.')),
                ('max_time_slots', models.PositiveIntegerField(default=10, help_text='Nombre maximal de créneaux (ProviderTimeSlot) que le prestataire peut créer.')),
                ('highlight_in_search', models.BooleanField(default=False, help_text='Les services de ce plan remontent un peu plus dans les listes.')),
                ('can_export_reports', models.BooleanField(default=False, help_text='Peut exporter des rapports (pdf/excel) sur ses commandes.')),
                ('is_default', models.BooleanField(default=False, help_text='Plan par défaut pour tout nouveau prestataire.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
            },
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='allow_urgent',
            field=models.BooleanField(default=False, help_text='Accepter les demandes urgentes pour ce service.'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='urgent_extra_percent',
            field=models.PositiveIntegerField(default=20, help_text='Majoration en % pour une commande urgente (ex : 20 = +20%).'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='urgent_max_per_day',
            field=models.PositiveIntegerField(default=3, help_text='Nombre max de commandes urgentes par jour (pour ce service).'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Commande marquée comme urgente.'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, help_text='Prix total avec éventuellement l’urgence.', null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='urgent_fee',
            field=models.PositiveIntegerField(blank=True, help_text='Montant de la majoration d’urgence.', null=True),
        ),
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('trial', 'Essai'), ('cancelled', 'Résilié'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Date de fin (optionnelle, pour plans sans reconduction).', null=True)),
                ('auto_renew', models.BooleanField(default=False, help_text="Renouveler automatiquement (géré par l'admin / système de paiement).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes internes (ex: offert pour 3 mois, etc.).', null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.servicesubscriptionplan')),
            ],
            options={
                'verbose_name': 'Abonnement prestataire',
                'verbose_name_plural': 'Abonnements prestataires',
            },
        ),
    ]
