# Generated by Django 5.2.8 on 2025-12-03 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_servicesubscriptionplan_serviceoffer_allow_urgent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_providers', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement prestataire',
                'verbose_name_plural': 'Abonnements prestataires',
                'unique_together': {('client', 'provider')},
            },
        ),
    ]
