# Generated by Django 5.2.8 on 2025-11-21 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('student', 'Étudiant'), ('company', 'Entreprise'), ('provider', 'Prestataire de services')], max_length=20, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False, help_text="L'email de l'utilisateur est-il vérifié ?")),
                ('verification_code', models.CharField(blank=True, help_text='Code de vérification envoyé par email', max_length=6, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('student_school', models.CharField(blank=True, help_text='Établissement actuel (lycée, université, etc.)', max_length=150, null=True)),
                ('student_level', models.CharField(blank=True, choices=[('terminale', 'Terminale'), ('licence', 'Licence'), ('master', 'Master'), ('autre', 'Autre')], help_text="Niveau d'étude", max_length=20, null=True)),
                ('student_field', models.CharField(blank=True, help_text="Filière / domaine d'étude actuel ou souhaité", max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, help_text="Nom de l'entreprise", max_length=150, null=True)),
                ('company_position', models.CharField(blank=True, help_text='Poste occupé (RH, responsable, etc.)', max_length=150, null=True)),
                ('company_website', models.URLField(blank=True, help_text="Site web de l'entreprise", null=True)),
                ('company_description', models.TextField(blank=True, help_text="Description de l'entreprise", null=True)),
                ('provider_title', models.CharField(blank=True, help_text='Titre du profil (ex: Coiffeuse à domicile, Prof de maths, etc.)', max_length=150, null=True)),
                ('provider_category', models.CharField(blank=True, help_text='Type de service (Coiffure, Cuisine, Mécanique, Cours particuliers, ...)', max_length=100, null=True)),
                ('provider_experience_years', models.PositiveIntegerField(blank=True, help_text="Années d'expérience", null=True)),
                ('provider_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tarif horaire moyen', max_digits=10, null=True)),
                ('provider_is_available', models.BooleanField(default=True, help_text='Est-il/elle actuellement disponible pour des prestations ?')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
