# Generated by Django 5.2.8 on 2025-11-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_verified',
            field=models.BooleanField(default=False, help_text="indique si l'entreprise a ete verifie par l'equipe"),
        ),
    ]
