# Generated by Django 5.2.8 on 2025-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyverificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_trust_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=50, help_text='Score de confiance (0–100). 50 = neutre.'),
        ),
    ]
