# Generated by Django 5.2.8 on 2025-11-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_trust_update_profile_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_orientation_alerts',
            field=models.BooleanField(default=True, help_text='Recevoir des alertes quand une nouvelle offre correspond à mon orientation.'),
        ),
    ]
