# Generated by Django 5.2.8 on 2025-11-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_receive_orientation_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_email_as_client',
            field=models.BooleanField(default=True, help_text='Recevoir un email pour mes commandes de services et les alertes de recherche.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_email_as_provider',
            field=models.BooleanField(default=True, help_text='Recevoir un email quand quelqu’un commande un de mes services.'),
        ),
    ]
