# Generated by Django 5.2.8 on 2025-11-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_service_email_as_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_service_provider',
            field=models.BooleanField(default=False, help_text='Indique si l’utilisateur souhaite offrir des services.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_service_provider_verified',
            field=models.BooleanField(default=False, help_text="Coché par l'équipe. Permet de publier des services."),
        ),
    ]
