# Generated by Django 5.2.8 on 2025-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_is_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='provider_availability_notes',
            field=models.CharField(blank=True, help_text='Ex : Disponible seulement le week-end, après 18h, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='provider_unavailable_until',
            field=models.DateField(blank=True, help_text='Date jusqu’à laquelle le prestataire est indisponible (facultatif).', null=True),
        ),
    ]
