# Generated by Django 5.2.8 on 2025-12-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_provider_availability_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_end_time',
            field=models.TimeField(blank=True, help_text='Heure à laquelle tu arrêtes le chat (ex: 20:00).', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_start_time',
            field=models.TimeField(blank=True, help_text='Heure à partir de laquelle tu es généralement disponible pour le chat (ex: 09:00).', null=True),
        ),
    ]
