# Generated by Django 5.2.8 on 2025-12-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_chat_end_time_profile_chat_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_manual_enabled',
            field=models.BooleanField(default=True, help_text='Active ou désactive le chat manuellement.'),
        ),
    ]
