# Generated by Django 5.2.8 on 2025-12-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_chat_manual_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_chat_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
