# Generated by Django 5.2.8 on 2025-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_last_chat_seen_alter_profile_chat_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_document',
            field=models.FileField(blank=True, help_text="Document d'identité (CNI, carte étudiant, etc.).", null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_verified',
            field=models.BooleanField(default=False, help_text="Validé manuellement par l'équipe."),
        ),
    ]
