# Generated by Django 5.2.8 on 2025-12-17 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'Étudiant'), ('company', 'Entreprise'), ('provider', 'Prestataire')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
