# Generated by Django 5.2.8 on 2026-01-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_badge_userbadge'),
        ('stages', '0023_conversation_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_target_document',
            field=models.ForeignKey(blank=True, help_text='Le document vers lequel le QR code de la carte de visite va rediriger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_for_qr_profile', to='stages.studentdocument'),
        ),
    ]
