# Generated by Django 5.2.11 on 2026-03-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_qr_target_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a déjà vu la séquence complète au moins une fois"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_onboarding',
            field=models.BooleanField(default=True, help_text="Afficher les modals d'accueil (règles, fondements, etc.)"),
        ),
    ]
