# Generated by Django 5.2.11 on 2026-03-01 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_onboarding_completed_profile_show_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_chat_seen',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_end_time',
            field=models.TimeField(blank=True, help_text='Heure de fin de disponibilité du chat', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_start_time',
            field=models.TimeField(blank=True, help_text='Heure de début de disponibilité du chat', null=True),
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('reset_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'action_type', 'reset_date')},
            },
        ),
    ]
