# Generated by Django 5.2.11 on 2026-03-01 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_options_remove_profile_last_chat_seen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_see_stats',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_use_messaging',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_applications',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_premium_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_cv_monthly',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_interviews_monthly',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_offers_monthly',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_projects_monthly',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_tests_monthly',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='role_target',
            field=models.CharField(choices=[('student', 'Étudiant'), ('company', 'Entreprise'), ('provider', 'Prestataire')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
