# Generated by Django 5.2.11 on 2026-03-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_profile_options_profile_last_chat_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(blank=True, help_text='Code interne (ex: FREE_STUDENT, PRO_PROVIDER)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Plan par défaut pour le rôle cible'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_featured_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_time_slots',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_urgent_orders_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
