# Generated by Django 5.2.8 on 2026-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_subscriptionplan_code_subscriptionplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_challenges_monthly',
            field=models.IntegerField(default=0, help_text='Nombre de challenges publiables par mois'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_search_alerts',
            field=models.IntegerField(default=1, help_text="Nombre d'alertes de recherche actives autorisées"),
        ),
    ]
