# Generated by Django 5.2.11 on 2026-03-01 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICachedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_originale', models.TextField(verbose_name='Question originale')),
                ('question_normalisee', models.TextField(db_index=True, verbose_name='Question normalisée')),
                ('reponse', models.TextField(verbose_name='Réponse générée')),
                ('compteur_utilisation', models.PositiveIntegerField(default=1, verbose_name="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réponse IA en Cache',
                'verbose_name_plural': 'Réponses IA en Cache',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('history', models.JSONField(default=list, verbose_name='Historique (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de Chat IA',
                'verbose_name_plural': 'Sessions de Chat IA',
            },
        ),
    ]
