"""
Django settings for CampuHub project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join (BASE_DIR, 'templates')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x7u04l7m)+x=pyc(y!tr_b1wt3c=hw7)5)dxbpgoz)22ex6dw5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['campuhub.site', 'www.campuhub.site', '62.171.158.152', 'localhost', '127.0.0.1']

# Config SSL / CSRF pour la prod
CSRF_TRUSTED_ORIGINS = ['https://campuhub.site', 'https://www.campuhub.site']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'orientation',
    'stages',
    'services',
    'celery',
    'channels',
    'incubation',
    'ai_assistant',
    'payments',
    'django_prometheus',
]
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.EmailVerificationRequiredMiddleware',
    'accounts.middleware.SubscriptionMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'CampuHub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stages.context_processors.student_todo_badge',
                'stages.context_processors.messaging_counts',
                "stages.context_processors.websocket_settings",
            ],
        },
    },
]
# Appels audio/vidéo via un fournisseur externe (Daily, Whereby, etc.)
CALL_PROVIDER_BASE_URL = "https://votresousdomaine.daily.co/campushub-conv-"  
# ou par ex :
# CALL_PROVIDER_BASE_URL = "https://votresousdomaine.whereby.com/campushub-conv-"
ASGI_APPLICATION = "CampuHub.asgi.application"

WSGI_APPLICATION = 'CampuHub.wsgi.application'
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}
# ⚙️ Limites upload documents étudiants
MAX_STUDENT_DOC_SIZE = 5 * 1024 * 1024  # 5 Mo

ALLOWED_STUDENT_DOC_EXTS = [
    "pdf", "doc", "docx", "odt",
    "png", "jpg", "jpeg",
]
# DAILY_API_KEY=ton_api_key_daily_ici
# DAILY_DOMAIN=ton_domaine_daily_co_ici

# settings.py

# import os

# DAILY_API_KEY = os.getenv("DAILY_API_KEY", "")
# DAILY_DOMAIN = os.getenv("DAILY_DOMAIN", "")  # ex: "campushub.daily.co"
# Optionnel : limite de documents par étudiant
MAX_STUDENT_DOCS_PER_USER = 50

# Limite de messages par minute
CHAT_MAX_MESSAGES_PER_MINUTE = 10  # à adapter
MAX_AVATAR_SIZE_MB = 20  # taille max en méga-octets
ALLOWED_AVATAR_CONTENT_TYPES = (
    "image/jpeg",
    "image/png",
    "image/webp",
)
ALLOWED_AVATAR_EXTENSIONS = (".jpg", ".jpeg", ".png", ".webp")
import os
# CALL_WS_SCHEME=wss
# CALL_WS_HOST=mon-site.com
# CALL_WS_PORT=""       # pas de port → utilise 443/80 du navigateur
# Dev: runserver sur 8000, Daphne sur 8001
# Prod: tout derrière nginx sur le même host (pas de port explicite)
CALL_WS_SCHEME = os.environ.get("CALL_WS_SCHEME", "ws")        # ou "wss" en prod
CALL_WS_HOST   = os.environ.get("CALL_WS_HOST", "127.0.0.1")   # ton domaine en prod
CALL_WS_PORT   = os.environ.get("CALL_WS_PORT", "8001")        # "" en prod si même port que HTTP
ADMINS = [
    ("Admin", "siddick369@gmail.com"),
]
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'campushub_db'),
        'USER': os.getenv('DB_USER', 'campushub_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'campushub_pass'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "close-expired-offers-every-night": {
        "task": "stages.tasks.close_expired_offers_task",
        "schedule": crontab(hour=3, minute=0),  # tous les jours à 03h00
    },
    "remind-conversation-messages-every-morning": {
        "task": "stages.tasks.remind_conversation_messages_task",
        "schedule": crontab(hour=9, minute=30),
    },
    "recompute-trust-scores-every-night": {
        "task": "accounts.tasks.recompute_all_trust_scores_task",
        "schedule": crontab(hour=1, minute=0),  # à 01h00 chaque nuit
    },
    "expire-old-service-orders-every-hour": {
        "task": "services.tasks.expire_old_service_orders",
        "schedule": crontab(minute=0),  # toutes les heures
    },
    "notify-favorite-services-nearly-expired-every-hour": {
        "task": "services.tasks.notify_favorite_services_nearly_expired",
        "schedule": 60.0,  # toutes les heures
    },
    "remind-unread-applications-every-morning": {
        "task": "stages.tasks.remind_unread_applications_task",
        "schedule": crontab(hour=9, minute=0),  # tous les jours à 09h00
    },
    "send-daily-student-todo-emails-every-morning": {
        "task": "stages.tasks.send_daily_student_todo_emails_task",
        "schedule": crontab(hour=8, minute=0),  # tous les jours à 08:00
    },
}

import os
from celery.schedules import crontab

# URL de ton site (pour les liens dans les emails, notifications, etc.)
SITE_BASE_URL = "https://campuhub.site"

# -------------------------------
# PAIEMENTS (CinetPay & Flutterwave)
# -------------------------------
CINETPAY_SITE_ID = os.getenv("CINETPAY_SITE_ID", "123456") # Remplacer par ton Site ID réel
CINETPAY_API_KEY = os.getenv("CINETPAY_API_KEY", "apikey")   # Remplacer par ton API Key réelle

FLUTTERWAVE_SECRET_KEY = os.getenv("FLUTTERWAVE_SECRET_KEY", "FLWSECK-xxxx")
FLUTTERWAVE_PUBLIC_KEY = os.getenv("FLUTTERWAVE_PUBLIC_KEY", "FLWPUBK-xxxx")
FLUTTERWAVE_SECRET_HASH = os.getenv("FLUTTERWAVE_SECRET_HASH", "mysupersecret")

# -------------------------------
# CELERY / REDIS
# -------------------------------

# Le broker (Redis dans ton docker-compose)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")

# Facultatif mais conseillé : backend pour stocker les résultats de tâches
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/1")

# Format de sérialisation
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Fuseau horaire (important pour les tâches planifiées)
CELERY_TIMEZONE = "Africa/Douala"
CELERY_ENABLE_UTC = False
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True
from .info import *




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER 
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD 
EMAIL_PORT = EMAIL_PORT 


# EMAIL_HOST = 'smtp-relay.brevo.com'
# EMAIL_PORT = 2525
# EMAIL_USE_TLS = True

# # --- TES IDENTIFIANTS BREVO ---
# # L'identifiant que Brevo t'a donné (celui de ton message)
# EMAIL_HOST_USER = '9f4b2a001@smtp-brevo.com'

# # Ta NOUVELLE clé secrète (que tu vas générer, pas celle postée ici)
# EMAIL_HOST_PASSWORD = 'K7VXJCdE8cx3rDmY'

# # --- TRES IMPORTANT ---
# # Ici, mets l'email avec lequel tu as créé le compte Brevo (ex: alexis@gmail.com)
# # C'est l'adresse que les gens verront comme expéditeur.
# DEFAULT_FROM_EMAIL = 'sasukenozel@gmail.com'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL ='/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redis/Cache Configuration for production (Docker)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_CACHE_URL", f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# The CELERY settings are already defined above using os.getenv in lines 218-229.

# -------------------------------
# SECURITY LOGGING (Fintech Mode)
# -------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 30,  # 30 days retention
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Ensure logs directory exists
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)