# Generated by Django 5.2.8 on 2025-11-23 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orientation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivation_letter', models.TextField(blank=True, help_text='Lettre de motivation / message enregistré avec la candidature.', null=True)),
                ('status', models.CharField(choices=[('submitted', 'Envoyée'), ('viewed', 'Consultée'), ('shortlisted', 'Pré-sélectionné'), ('rejected', 'Refusée'), ('accepted', 'Acceptée'), ('withdrawn', 'Retirée par le candidat')], default='submitted', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, help_text='Dernière fois où le statut a été mis à jour.', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text="Quand l'entreprise a consulté la candidature.", null=True)),
                ('is_withdrawn', models.BooleanField(default=False, help_text='Le candidat a-t-il retiré sa candidature ?')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('company_note', models.TextField(blank=True, help_text="Notes internes de l'entreprise sur la candidature.", null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text="Note interne (1–5) donnée par l'entreprise au candidat.", null=True)),
                ('source', models.CharField(choices=[('platform', 'Trouvée sur CampusHub'), ('referral', 'Recommandation'), ('external', 'Lien externe'), ('other', 'Autre')], default='platform', help_text="Comment le candidat a découvert l'offre.", max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StageOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name_snapshot', models.CharField(blank=True, help_text="Nom de l'entreprise au moment de la création de l'offre.", max_length=200, null=True)),
                ('reference', models.CharField(blank=True, help_text="Référence interne de l'offre (ex: STG-2025-001).", max_length=30, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contract_type', models.CharField(choices=[('internship', 'Stage'), ('apprenticeship', 'Alternance'), ('job', 'Premier emploi')], default='internship', max_length=20)),
                ('experience_level', models.CharField(choices=[('none', 'Débutant / Sans expérience'), ('junior', 'Junior (0–2 ans)'), ('mid', 'Intermédiaire (2–5 ans)')], default='none', help_text="Niveau d'expérience attendu.", max_length=10)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('location_type', models.CharField(choices=[('onsite', 'Présentiel'), ('remote', 'À distance'), ('hybrid', 'Hybride')], default='onsite', max_length=10)),
                ('open_positions', models.PositiveIntegerField(default=1, help_text='Nombre de postes à pourvoir.')),
                ('duration_months', models.PositiveIntegerField(blank=True, help_text='Durée approximative en mois.', null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Salaire / indemnité minimum (ex: en FCFA).', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Salaire / indemnité maximum.', null=True)),
                ('required_level', models.CharField(blank=True, help_text='Niveau minimum (ex: Bac+1, Licence 2...).', max_length=100, null=True)),
                ('language_requirements', models.CharField(blank=True, help_text='Ex: Français courant, Anglais B2, bilingue...', max_length=200, null=True)),
                ('skills_required', models.TextField(blank=True, help_text='Compétences techniques OBLIGATOIRES.', null=True)),
                ('skills_nice_to_have', models.TextField(blank=True, help_text='Compétences appréciées mais facultatives.', null=True)),
                ('soft_skills_required', models.TextField(blank=True, help_text='Compétences humaines (rigueur, communication...).', null=True)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, help_text='Missions / responsabilités détaillées.', null=True)),
                ('benefits', models.TextField(blank=True, help_text='Avantages (tickets resto, primes, formation...).', null=True)),
                ('application_deadline', models.DateField(blank=True, help_text='Date limite pour postuler.', null=True)),
                ('max_applicants', models.PositiveIntegerField(blank=True, help_text='Optionnel : nombre max de candidatures à accepter.', null=True)),
                ('external_apply_url', models.URLField(blank=True, help_text='Lien vers une page externe de candidature (si besoin).', null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('closed', 'Clôturée'), ('archived', 'Archivée')], default='published', help_text="État de l'offre dans le cycle de vie.", max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text="Mettre en avant cette offre sur la page d'accueil.")),
                ('views_count', models.PositiveIntegerField(default=0, help_text="Nombre de fois que l'offre a été vue.")),
                ('applications_count', models.PositiveIntegerField(default=0, help_text='Nombre de candidatures reçues (dénormalisé pour la perf).')),
                ('is_active', models.BooleanField(default=True, help_text="Permet de masquer l'offre sans la supprimer.")),
                ('company', models.ForeignKey(help_text="Utilisateur avec rôle 'company'.", on_delete=django.db.models.deletion.CASCADE, related_name='stage_offers', to=settings.AUTH_USER_MODEL)),
                ('related_tracks', models.ManyToManyField(blank=True, help_text='Filières qui correspondent bien à cette offre.', related_name='stage_offers', to='orientation.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notif_type', models.CharField(choices=[('new_application', 'Nouvelle candidature'), ('status_update', 'Mise à jour de candidature'), ('general', 'Notification générale')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stages.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stages.stageoffer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='stages.stageoffer'),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='students/documents/')),
                ('title', models.CharField(blank=True, help_text="Nom du document (ex: 'CV 2025 FR', 'Portfolio design').", max_length=150, null=True)),
                ('doc_type', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Lettre de motivation'), ('portfolio', 'Portfolio'), ('other', 'Autre')], default='cv', max_length=20)),
                ('language', models.CharField(blank=True, help_text='Langue principale du document (ex: Français, Anglais).', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text="Notes internes pour l'étudiant (où il a utilisé ce doc, etc.).", null=True)),
                ('is_default_cv', models.BooleanField(default=False, help_text="CV principal à proposer par défaut lors d'une candidature.")),
                ('is_public', models.BooleanField(default=False, help_text='Visible par les entreprises (ex: profil public).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(blank=True, help_text='CV utilisé pour cette candidature.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.studentdocument'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('offer', 'student')},
        ),
    ]
