# Generated by Django 5.2.8 on 2025-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageoffer',
            name='applications_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de candidatures reçues (mis à jour automatiquement).'),
        ),
        migrations.AlterField(
            model_name='stageoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stageoffer',
            name='max_applicants',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre max de candidatures à accepter (optionnel).', null=True),
        ),
        migrations.AlterField(
            model_name='stageoffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('archived', 'Archivée')], default='published', max_length=20),
        ),
    ]
