# Generated by Django 5.2.8 on 2025-11-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_stageoffer_applications_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text="rappel a deja ete envoyer a l'entreprise pour cette candidature."),
        ),
    ]
