# Generated by Django 5.2.8 on 2025-11-25 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_application_reminder_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note globale (1 à 5).')),
                ('comment', models.TextField(blank=True, help_text="Retour libre sur l'expérience en entreprise.", null=True)),
                ('is_public', models.BooleanField(default=True, help_text="Si cochée, l'avis peut être affiché sur la page publique de l'entreprise.")),
                ('application', models.OneToOneField(blank=True, help_text='Candidature associée (facultatif mais pratique).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='stages.application')),
                ('company', models.ForeignKey(help_text='Entreprise évaluée.', on_delete=django.db.models.deletion.CASCADE, related_name='received_stage_reviews', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(help_text="Offre pour laquelle l'avis est donné.", on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stages.stageoffer')),
                ('student', models.ForeignKey(help_text="Étudiant qui laisse l'avis.", on_delete=django.db.models.deletion.CASCADE, related_name='stage_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis de stage',
                'verbose_name_plural': 'Avis de stage',
                'unique_together': {('offer', 'student')},
            },
        ),
    ]
