# Generated by Django 5.2.8 on 2025-11-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_stagereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_fingerprint',
            field=models.CharField(blank=True, help_text="Empreinte de l'appareil (IP + User-Agent hashé) pour limiter les multi-comptes.", max_length=255, null=True),
        ),
    ]
