# Generated by Django 5.2.8 on 2025-11-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_conversationreport_conversationblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='company_muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='company_strike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='student_muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='student_strike_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
