# Generated by Django 5.2.8 on 2025-11-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_conversation_company_muted_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('normal', 'Message normal'), ('systeme', 'Message système')], default='normal', help_text='Permet de distinguer les messages nirmaux des messages systeme', max_length=20),
        ),
    ]
