# Generated by Django 5.2.8 on 2025-11-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_message_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='company_last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='student_last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
