# Generated by Django 5.2.8 on 2025-11-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0010_conversation_company_last_reminder_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_archived_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_archived_student',
            field=models.BooleanField(default=False),
        ),
    ]
