# Generated by Django 5.2.8 on 2025-11-27 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0011_conversation_is_archived_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Nom court (ex: 'Merci candidature').", max_length=100)),
                ('text', models.TextField(help_text='Texte qui sera inséré dans le chat.')),
                ('for_role', models.CharField(blank=True, choices=[('company', 'Entreprise'), ('student', 'Étudiant')], help_text='Rôle ciblé (company / student). Null = tous.', max_length=20, null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Si coché, visible pour tous les utilisateurs du rôle ciblé.')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Propriétaire de ce modèle. Null = modèle global (admin).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réponse rapide',
                'verbose_name_plural': 'Réponses rapides',
            },
        ),
    ]
