# Generated by Django 5.2.8 on 2025-11-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0013_message_edited_at_message_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q', models.CharField(blank=True, help_text='Mot-clé (titre, compétences, description).', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='Ville recherchée (ex: Douala).', max_length=100, null=True)),
                ('contract_type', models.CharField(blank=True, help_text='Type de contrat (ex: full_time, internship...).', max_length=20, null=True)),
                ('location_type', models.CharField(blank=True, help_text='remote / onsite / hybrid.', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_search_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Alerte de recherche d'offre",
                'verbose_name_plural': "Alertes de recherche d'offres",
            },
        ),
        migrations.CreateModel(
            name='SavedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='stages.stageoffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offre sauvegardée',
                'verbose_name_plural': 'Offres sauvegardées',
                'unique_together': {('student', 'offer')},
            },
        ),
    ]
