# Generated by Django 5.2.8 on 2025-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0014_jobsearchalert_savedoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageoffer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stageoffer',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
