# Generated by Django 5.2.8 on 2025-11-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceoffer_slug'),
        ('stages', '0015_alter_stageoffer_slug_alter_stageoffer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='service_order',
            field=models.OneToOneField(blank=True, help_text='Conversation liée à une commande de service', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='services.serviceorder'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='application',
            field=models.OneToOneField(blank=True, help_text='Conversation liée à une candidature de stage', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='stages.application'),
        ),
    ]
