# Generated by Django 5.2.8 on 2025-12-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0016_conversation_service_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Fichier envoyé dans le chat (image, PDF, doc...).', max_length=255, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', help_text='Type MIME détecté', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0, help_text='Taille du fichier en octets'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
