# Generated by Django 5.2.8 on 2025-12-03 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0017_message_attachment_message_attachment_mime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_session', to='stages.conversation')),
                ('host', models.ForeignKey(blank=True, help_text="Utilisateur qui a démarré l'appel (modérateur).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
