# Generated by Django 5.2.8 on 2025-12-08 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0018_conversationcallsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='is_protected',
            field=models.BooleanField(default=True, help_text="Si coché, le fichier n'est accessible qu'à l'étudiant et aux personnes autorisées."),
        ),
        migrations.CreateModel(
            name='ConversationCallRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_room_name', models.CharField(max_length=200, unique=True)),
                ('daily_url', models.URLField(help_text='URL joinable de la room Daily')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_room', to='stages.conversation')),
            ],
        ),
        migrations.DeleteModel(
            name='ConversationCallSession',
        ),
    ]
