# Generated by Django 5.2.8 on 2025-12-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0020_companysubscriptionplan_companysubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='offers_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stages.stageoffer')),
            ],
        ),
    ]
