# Generated by Django 5.2.8 on 2026-01-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0002_participationchallenge_date_confirmation_etudiant_and_more'),
        ('stages', '0022_companyfeedbacke'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='participation',
            field=models.OneToOneField(blank=True, help_text="Conversation liée à une soumission validée d'un challenge", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='incubation.participationchallenge'),
        ),
    ]
