# Generated by Django 5.2.11 on 2026-03-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0025_alter_stagereview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformreview',
            name='role_at_review',
            field=models.CharField(choices=[('student', 'Étudiant'), ('company', 'Entreprise'), ('provider', 'Prestataire de services')], max_length=20),
        ),
    ]
