# Generated by Django 5.2.11 on 2026-03-03 06:45

import django.db.models.deletion
import incubation.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0026_alter_platformreview_role_at_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='cv_templates/previews/')),
                ('template_file', models.CharField(help_text='Chemin du template HTML (ex: stages/cv_templates/modern.html)', max_length=200)),
                ('css_class', models.CharField(blank=True, help_text='Classe CSS racine', max_length=50)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Template CV',
                'verbose_name_plural': 'Templates CV',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Fichier envoyé dans le chat (image, PDF, doc...).', max_length=255, null=True, upload_to='chat_attachments/', validators=[incubation.validators.valider_taille_fichier_5mo]),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='file',
            field=models.ImageField(upload_to='offers_images/', validators=[incubation.validators.valider_taille_image_2mo]),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(upload_to='students/documents/', validators=[incubation.validators.valider_taille_fichier_5mo]),
        ),
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Mon CV', max_length=100, verbose_name='Nom du CV')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('professional_title', models.CharField(blank=True, max_length=150, verbose_name='Titre professionnel')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cv_photos/')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé professionnel')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color', max_length=7)),
                ('secondary_color', models.CharField(default='#1e293b', max_length=7)),
                ('font_family', models.CharField(choices=[('inter', 'Inter'), ('roboto', 'Roboto'), ('playfair', 'Playfair Display'), ('lora', 'Lora'), ('montserrat', 'Montserrat')], default='inter', max_length=30)),
                ('photo_frame', models.CharField(choices=[('circle', 'Cercle'), ('square', 'Carré'), ('rounded', 'Arrondi'), ('banner', 'Bande latérale'), ('none', 'Sans photo')], default='circle', max_length=20)),
                ('skill_display', models.CharField(choices=[('bars', 'Barres de progression'), ('dots', 'Points'), ('text', 'Texte simple')], default='bars', max_length=10)),
                ('section_order', models.JSONField(blank=True, default=list, help_text="Ordre des sections: ['experience','education','skills','languages','projects','certifications','interests']")),
                ('is_draft', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False, help_text="CV principal de l'utilisateur")),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('applications_used_count', models.PositiveIntegerField(default=0)),
                ('last_ats_score', models.PositiveIntegerField(blank=True, help_text='Dernier score ATS (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_profiles', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.cvtemplate')),
            ],
            options={
                'verbose_name': 'Profil CV',
                'verbose_name_plural': 'Profils CV',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CVLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('A1', 'A1 — Découverte'), ('A2', 'A2 — Survie'), ('B1', 'B1 — Seuil'), ('B2', 'B2 — Avancé'), ('C1', 'C1 — Autonome'), ('C2', 'C2 — Maîtrise'), ('native', 'Langue maternelle')], default='B1', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, help_text='Ex: 03/2024', max_length=20)),
                ('end_date', models.CharField(blank=True, help_text='Ex: 08/2024 ou vide si en poste', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('from_application', models.ForeignKey(blank=True, help_text='Si créé automatiquement depuis une candidature CampusHub', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.application')),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CVEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CVCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=150)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField(help_text='Score global ATS 0-100')),
                ('keyword_score', models.PositiveIntegerField(default=0)),
                ('action_verbs_score', models.PositiveIntegerField(default=0)),
                ('completeness_score', models.PositiveIntegerField(default=0)),
                ('formatting_score', models.PositiveIntegerField(default=0)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('weak_descriptions', models.JSONField(blank=True, default=list)),
                ('target_offer_title', models.CharField(blank=True, help_text="Offre ciblée pour l'optimisation", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé'), (4, 'Expert')], default=2)),
                ('category', models.CharField(choices=[('technical', 'Technique'), ('soft', 'Humaine')], default='technical', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot_data', models.JSONField(help_text='Snapshot complet du CV en JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='stages.cvprofile')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('cv_profile', 'version_number')},
            },
        ),
        migrations.DeleteModel(
            name='CompanySubscription',
        ),
        migrations.DeleteModel(
            name='CompanySubscriptionPlan',
        ),
    ]
