# Generated by Django 5.2.11 on 2026-03-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0028_seed_cv_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='job_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvprofile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
