# Generated by Django 5.2.8 on 2026-01-07 16:53

import django.core.validators
import django.db.models.deletion
import incubation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('couleur', models.CharField(default='#3B82F6', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cahier_des_charges', models.FileField(blank=True, help_text='Cahier des charges (PDF, DOC). Max 5 Mo.', null=True, upload_to='challenges/docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), incubation.validators.valider_taille_fichier_5mo])),
                ('image_illustration', models.ImageField(blank=True, help_text="Image d'illustration. Max 2 Mo.", null=True, upload_to='challenges/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), incubation.validators.valider_taille_image_2mo])),
                ('recompense', models.CharField(help_text='ex: Stage, Prime, Incubation', max_length=100)),
                ('date_limite', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_lances', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_rendu', models.FileField(help_text='Votre solution (PDF, ZIP, RAR). Max 5 Mo.', upload_to='rendus_challenges/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar', 'doc', 'docx']), incubation.validators.valider_taille_fichier_5mo])),
                ('description_solution', models.TextField(blank=True, help_text='Explication rapide de la solution')),
                ('lien_externe', models.URLField(blank=True, help_text='Lien GitHub ou Drive si fichier lourd', null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('est_vainqueur', models.BooleanField(default=False)),
                ('feedback_entreprise', models.TextField(blank=True, help_text="Retour de l'entreprise sur ce travail", null=True)),
                ('candidat', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incubation.challengeentreprise')),
            ],
            options={
                'verbose_name': 'Participation / Soumission',
                'unique_together': {('candidat', 'challenge')},
            },
        ),
        migrations.AddField(
            model_name='challengeentreprise',
            name='participants',
            field=models.ManyToManyField(related_name='challenges_participes', through='incubation.ParticipationChallenge', to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='ProjetInnovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_courte', models.CharField(max_length=255)),
                ('description_complete', models.TextField()),
                ('image_couverture', models.ImageField(blank=True, help_text='Format: JPG, PNG, WEBP. Max 2 Mo.', null=True, upload_to='projets/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), incubation.validators.valider_taille_image_2mo])),
                ('video_demo', models.URLField(blank=True, help_text='Lien YouTube/Vimeo du pitch', null=True)),
                ('stade', models.CharField(choices=[('IDEE', "Phase d'Idéation"), ('MVP', 'Prototype (MVP)'), ('DEV', 'En développement'), ('LIVE', 'Projet Lancé')], default='IDEE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competences_recherchees', models.ManyToManyField(blank=True, to='incubation.competence')),
                ('equipe', models.ManyToManyField(blank=True, help_text="Les membres de l'équipe projet", limit_choices_to={'role': 'student'}, related_name='projets_rejoints', to='accounts.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='projets_aimes', to='accounts.profile')),
                ('porteur', models.ForeignKey(help_text="L'étudiant créateur du projet", limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets_innovants_crees', to='accounts.profile')),
            ],
        ),
    ]
