# Generated by Django 5.2.8 on 2026-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationchallenge',
            name='date_confirmation_etudiant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participationchallenge',
            name='note_litige',
            field=models.TextField(blank=True, help_text="Explication du problème par l'étudiant"),
        ),
        migrations.AddField(
            model_name='participationchallenge',
            name='statut_recompense',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SENT', "Envoyé par l'entreprise"), ('RECEIVED', "Confirmé par l'étudiant"), ('DISPUTE', 'Litige / Non reçu')], default='PENDING', max_length=10),
        ),
    ]
