# Generated by Django 5.2.8 on 2026-01-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_successstory'),
        ('incubation', '0002_participationchallenge_date_confirmation_etudiant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Le mot-clé recherché', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_alerts', to='accounts.profile')),
            ],
            options={
                'unique_together': {('user', 'query')},
            },
        ),
    ]
