# Generated by Django 5.2.8 on 2026-01-08 12:48

import django.core.validators
import django.db.models.deletion
import incubation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_successstory'),
        ('incubation', '0003_challengesearchalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetinnovation',
            name='besoins',
            field=models.TextField(blank=True, help_text='Ex: Financement, un développeur, un local, des conseils...', verbose_name='De quoi avez-vous besoin ?'),
        ),
        migrations.AddField(
            model_name='projetinnovation',
            name='dossier_projet',
            field=models.FileField(blank=True, help_text='Business Plan, Plaquette ou Présentation détaillée (Max 5Mo).', null=True, upload_to='projets/docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx']), incubation.validators.valider_taille_fichier_5mo], verbose_name='Dossier de présentation (PDF/PPT)'),
        ),
        migrations.AddField(
            model_name='projetinnovation',
            name='lien_whatsapp',
            field=models.URLField(blank=True, help_text='Lien direct WhatsApp (ex: https://wa.me/2376...)', null=True),
        ),
        migrations.AddField(
            model_name='projetinnovation',
            name='secteur',
            field=models.CharField(choices=[('TECH', 'Informatique & Technologie'), ('AGRO', 'Agriculture & Agroalimentaire'), ('IND', 'Industrie & Mécanique'), ('BTP', 'Génie Civil & Architecture'), ('ART', 'Art, Mode & Culture'), ('SERV', 'Services & Commerce'), ('SANTE', 'Santé & Bien-être'), ('AUTRE', 'Autre')], default='TECH', max_length=10, verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='competences_recherchees',
            field=models.ManyToManyField(blank=True, to='incubation.competence', verbose_name='Profils recherchés'),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='description_complete',
            field=models.TextField(verbose_name='Détails du projet'),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='description_courte',
            field=models.CharField(max_length=255, verbose_name="Phrase d'accroche"),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='equipe',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='projets_rejoints', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='image_couverture',
            field=models.ImageField(blank=True, help_text='Une belle image pour représenter votre projet (Produit, Logo, Maquette...)', null=True, upload_to='projets/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp']), incubation.validators.valider_taille_image_2mo]),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='porteur',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets_innovants_crees', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='stade',
            field=models.CharField(choices=[('IDEE', "J'ai juste une idée 💡"), ('MVP', "J'ai un prototype / échantillon 🛠️"), ('LIVE', 'Le projet est déjà lancé 🚀')], default='IDEE', max_length=10),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='titre',
            field=models.CharField(max_length=100, verbose_name='Nom du projet'),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='video_demo',
            field=models.URLField(blank=True, help_text='Si vous avez une vidéo de présentation.', null=True, verbose_name='Lien Vidéo (YouTube/Vimeo)'),
        ),
        migrations.CreateModel(
            name='ProjetSearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Le mot-clé recherché', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_alerts', to='accounts.profile')),
            ],
            options={
                'unique_together': {('user', 'query')},
            },
        ),
    ]
