# Generated by Django 5.2.8 on 2026-01-08 13:00

import django.core.validators
import incubation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0004_projetinnovation_besoins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetinnovation',
            name='cherche_financement',
            field=models.BooleanField(default=False, verbose_name='Je cherche des investisseurs'),
        ),
        migrations.AddField(
            model_name='projetinnovation',
            name='est_en_recrutement',
            field=models.BooleanField(default=False, verbose_name='Je cherche des co-équipiers'),
        ),
        migrations.AddField(
            model_name='projetinnovation',
            name='lien_instagram',
            field=models.URLField(blank=True, help_text='Ex: https://instagram.com/mon_projet', null=True),
        ),
        migrations.AddField(
            model_name='projetinnovation',
            name='lien_linkedin',
            field=models.URLField(blank=True, help_text='Ex: https://linkedin.com/in/...', null=True),
        ),
        migrations.AddField(
            model_name='projetinnovation',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site Web / Portfolio'),
        ),
        migrations.AddField(
            model_name='projetinnovation',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='besoins',
            field=models.TextField(blank=True, help_text='Ex: Financement, un développeur, un local, des conseils...', verbose_name='Détails des besoins'),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='dossier_projet',
            field=models.FileField(blank=True, help_text='Business Plan, Plaquette (Max 5Mo).', null=True, upload_to='projets/docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx']), incubation.validators.valider_taille_fichier_5mo], verbose_name='Dossier de présentation'),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='image_couverture',
            field=models.ImageField(blank=True, help_text='Format: JPG, PNG, WEBP. Max 2 Mo.', null=True, upload_to='projets/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp']), incubation.validators.valider_taille_image_2mo]),
        ),
        migrations.AlterField(
            model_name='projetinnovation',
            name='video_demo',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Vidéo'),
        ),
    ]
