# Generated by Django 5.2.8 on 2026-01-08 13:08

import django.core.validators
import incubation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0005_projetinnovation_cherche_financement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeentreprise',
            name='competences_cibles',
            field=models.ManyToManyField(blank=True, help_text="Quels types d'étudiants ciblez-vous ?", to='incubation.competence', verbose_name='Compétences recherchées'),
        ),
        migrations.AddField(
            model_name='challengeentreprise',
            name='format_rendu',
            field=models.CharField(choices=[('PDF', 'Dossier PDF / SlideDeck'), ('VIDEO', 'Vidéo de présentation'), ('CODE', 'Code Source / Lien GitHub'), ('PHYSIQUE', 'Prototype Physique / Maquette'), ('LIBRE', 'Format Libre')], default='PDF', max_length=10, verbose_name='Format attendu pour la réponse'),
        ),
        migrations.AddField(
            model_name='challengeentreprise',
            name='secteur',
            field=models.CharField(choices=[('TECH', 'Informatique & Tech'), ('AGRO', 'Agriculture & Agro.'), ('IND', 'Industrie & BTP'), ('ART', 'Design, Art & Mode'), ('MARKETING', 'Marketing & Vente'), ('STRAT', 'Stratégie & Gestion'), ('AUTRE', 'Autre')], default='TECH', max_length=15),
        ),
        migrations.AddField(
            model_name='challengeentreprise',
            name='type_challenge',
            field=models.CharField(choices=[('HACK', 'Hackathon / Dev (Tech)'), ('CREA', 'Concours Créatif (Design/Logo/Vidéo)'), ('ETUDE', 'Étude de Cas / Stratégie (Business)'), ('PROB', 'Résolution de Problème (Ingénierie)')], default='HACK', max_length=10),
        ),
        migrations.AlterField(
            model_name='challengeentreprise',
            name='cahier_des_charges',
            field=models.FileField(blank=True, help_text='Un document détaillé pour guider les étudiants (PDF, DOC). Max 5 Mo.', null=True, upload_to='challenges/docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), incubation.validators.valider_taille_fichier_5mo], verbose_name='Document Support (Brief / Cahier des charges)'),
        ),
        migrations.AlterField(
            model_name='challengeentreprise',
            name='date_limite',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='challengeentreprise',
            name='description',
            field=models.TextField(help_text='Expliquez le contexte, le problème à résoudre et vos attentes.', verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='challengeentreprise',
            name='image_illustration',
            field=models.ImageField(blank=True, help_text='Une image pour donner envie de participer.', null=True, upload_to='challenges/img/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp']), incubation.validators.valider_taille_image_2mo]),
        ),
        migrations.AlterField(
            model_name='challengeentreprise',
            name='recompense',
            field=models.CharField(help_text="Soyez précis : 'Stage rémunéré', 'Chèque de 50.000 FCFA', 'Mentorat'...", max_length=100, verbose_name='À gagner (Récompense)'),
        ),
        migrations.AlterField(
            model_name='challengeentreprise',
            name='titre',
            field=models.CharField(max_length=150, verbose_name='Titre du Challenge'),
        ),
    ]
