# Generated by Django 5.2.8 on 2026-01-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0006_challengeentreprise_competences_cibles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name="Titre de l'actualité")),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, help_text='Une photo pour illustrer cette étape (Optionnel)', null=True, upload_to='projets/updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='incubation.projetinnovation')),
            ],
            options={
                'verbose_name': 'Actualité du projet',
                'ordering': ['-created_at'],
            },
        ),
    ]
