# Generated by Django 5.2.8 on 2026-01-08 19:40

import django.core.validators
import incubation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0007_projetupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetupdate',
            name='image',
            field=models.ImageField(blank=True, help_text='Une photo pour illustrer cette étape (Optionnel)', null=True, upload_to='projets/updates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp']), incubation.validators.valider_taille_image_2mo]),
        ),
    ]
