# Generated by Django 5.2.8 on 2026-01-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0008_alter_projetupdate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms_prenoms', models.CharField(max_length=200, verbose_name='Noms et Prénoms')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse_email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('filiere', models.CharField(max_length=100, verbose_name='Filière')),
                ('moyenne_generale', models.FloatField(verbose_name='Moyenne Générale')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='talents/')),
                ('competences', models.ManyToManyField(blank=True, to='incubation.competence')),
            ],
            options={
                'ordering': ['-moyenne_generale'],
            },
        ),
    ]
