# Generated by Django 5.2.8 on 2026-01-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0009_etudianttalent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='couleur',
        ),
    ]
