# Generated by Django 5.2.8 on 2026-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0011_interviewsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='cv_text',
            field=models.TextField(blank=True, verbose_name='Texte du CV'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_description',
            field=models.TextField(blank=True, verbose_name="Description de l'offre"),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
