# Generated by Django 5.2.8 on 2026-02-19 07:17

import django.core.validators
import incubation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0012_interviewsession_cv_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetinnovation',
            name='image_couverture',
            field=models.ImageField(blank=True, help_text='Format: JPG, PNG, WEBP. Max 2 Mo.', null=True, upload_to='projets/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'jpeg']), incubation.validators.valider_taille_image_2mo]),
        ),
    ]
