# Generated by Django 5.2.8 on 2026-02-19 08:13

import django.core.validators
import incubation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0013_alter_projetinnovation_image_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeentreprise',
            name='image_illustration',
            field=models.ImageField(blank=True, help_text='Une image pour donner envie de participer.', null=True, upload_to='challenges/img/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'jpeg']), incubation.validators.valider_taille_image_2mo]),
        ),
    ]
