# Generated by Django 5.2.11 on 2026-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0014_alter_challengeentreprise_image_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='couleur',
            field=models.CharField(default='#3B82F6', help_text='Code Hex (ex: #3B82F6)', max_length=7),
        ),
    ]
