# Generated by Django 5.2.8 on 2025-11-23 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, help_text='Secteur (IT, Finance, Santé...).', max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_tasks', models.TextField(blank=True, help_text='Missions principales.', null=True)),
                ('required_hard_skills', models.TextField(blank=True, help_text='Compétences techniques importantes.', null=True)),
                ('required_soft_skills', models.TextField(blank=True, help_text='Compétences humaines (communication, équipe...).', null=True)),
                ('typical_salary_min', models.PositiveIntegerField(blank=True, help_text='Salaire de départ approximatif.', null=True)),
                ('typical_salary_max', models.PositiveIntegerField(blank=True, help_text='Salaire après quelques années.', null=True)),
                ('salary_currency', models.CharField(blank=True, default='FCFA', max_length=10)),
                ('demand_level', models.CharField(choices=[('high', 'Très recherché'), ('medium', 'Recherché'), ('low', 'Peu demandé')], default='medium', max_length=10)),
                ('remote_friendly', models.BooleanField(default=False, help_text='Compatible télétravail ?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('interest', 'Centres d’intérêt'), ('skill', 'Compétences'), ('personality', 'Personnalité'), ('value', 'Valeurs / Priorités')], default='interest', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(help_text='Code interne (ex: INF-LIC, DRT-MAS...).', max_length=20, unique=True)),
                ('domain', models.CharField(choices=[('stem', 'Sciences & Tech (STEM)'), ('business', 'Business & Management'), ('health', 'Santé'), ('social', 'Sciences sociales'), ('arts', 'Arts & Design'), ('other', 'Autre')], default='stem', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Accessible'), (2, 'Modérée'), (3, 'Exigeante'), (4, 'Très exigeante'), (5, 'Élite')], default=2)),
                ('typical_duration_years', models.PositiveSmallIntegerField(default=3, help_text='Durée typique des études (en années).')),
                ('description', models.TextField(blank=True, null=True)),
                ('main_skills', models.TextField(blank=True, help_text='Compétences techniques (séparées par des virgules).', null=True)),
                ('soft_skills', models.TextField(blank=True, help_text='Compétences humaines/comportementales.', null=True)),
                ('recommended_profiles', models.TextField(blank=True, help_text="Quel type d'élève est le plus adapté à cette filière ?", null=True)),
                ('future_outlook', models.CharField(choices=[('rising', 'Très porteur'), ('stable', 'Stable'), ('risky', 'En incertitude')], default='rising', help_text='Avenir global de la filière.', max_length=20)),
                ('color_hex', models.CharField(blank=True, help_text="Couleur (#3498db par ex) pour l'UI.", max_length=7, null=True)),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône (ex: 'fa-solid fa-laptop-code').", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrientationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scores_data', models.JSONField(blank=True, help_text='Détails des scores (filières, catégories).', null=True)),
                ('comment', models.TextField(blank=True, help_text='Note ou commentaire personnalisé.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suggested_tracks', models.ManyToManyField(blank=True, related_name='orientation_results', to='orientation.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='orientation.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('school_type', models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('online', 'En ligne'), ('other', 'Autre')], default='public', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('tuition_range', models.CharField(blank=True, help_text="Ex: '500k - 1M FCFA/an'.", max_length=100, null=True)),
                ('admission_level', models.CharField(blank=True, help_text='Ex: Bac, Bac+2...', max_length=100, null=True)),
                ('ranking_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score interne (0–10) pour classer les écoles.', max_digits=4, null=True)),
                ('is_partner', models.BooleanField(default=False, help_text='École partenaire officielle.')),
                ('tracks', models.ManyToManyField(blank=True, related_name='schools', to='orientation.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobTrackRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.PositiveSmallIntegerField(default=3, help_text='1 = lien faible, 5 = lien très fort.')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.job')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.track')),
            ],
            options={
                'unique_together': {('job', 'track')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='jobs', through='orientation.JobTrackRelevance', to='orientation.track'),
        ),
        migrations.CreateModel(
            name='ChoiceTrackScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=1, help_text='Points ajoutés pour cette filière si ce choix est choisi.')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.choice')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.track')),
            ],
            options={
                'unique_together': {('choice', 'track')},
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='choice_links', through='orientation.ChoiceTrackScore', to='orientation.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='orientation.tracktag'),
        ),
        migrations.CreateModel(
            name='OrientationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orientation.choice')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='orientation.orientationresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.question')),
            ],
            options={
                'unique_together': {('result', 'question')},
            },
        ),
    ]
