# Generated by Django 5.2.8 on 2025-11-27 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(help_text='URL complète de la playlist YouTube')),
                ('playlist_id', models.CharField(blank=True, help_text='ID YouTube automatique (ex: PLxyz...)', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('channel_name', models.CharField(max_length=150)),
                ('channel_url', models.URLField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('bilingual', 'Bilingue')], default='fr', max_length=20)),
                ('estimated_hours', models.PositiveIntegerField(default=0, help_text='Durée totale estimée (heures)')),
                ('video_count', models.PositiveIntegerField(default=0, help_text='Nombre de vidéos dans la playlist')),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('tracks', models.ManyToManyField(help_text='Filières associées à cette playlist', related_name='youtube_playlists', to='orientation.track')),
            ],
            options={
                'verbose_name': 'Playlist YouTube',
                'verbose_name_plural': 'Playlists YouTube',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserPlaylistProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_videos', models.PositiveIntegerField(default=0)),
                ('total_videos', models.PositiveIntegerField(default=0)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_watched', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('personal_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.youtubeplaylist')),
            ],
            options={
                'verbose_name': 'Progression Playlist',
                'verbose_name_plural': 'Progressions Playlists',
                'unique_together': {('user', 'playlist')},
            },
        ),
    ]
